set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -ag terminal-overrides ",*:Tc"
set -ga terminal-overrides ",*:Ss=\\E[%p1%d q:Se=\\E[2 q"
set -ga terminal-overrides ",*:sitm=\\E[3m:ritm=\\E[23m"
set -g mouse on

# Configure kaybindings
set -g prefix C-s
unbind C-b
set-window-option -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Gruvbox color pallete


# Configure status bar
set-option -g status-position top
set -g status-style bg=default

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
run '~/.tmux/plugins/tpm/tpm'
